# Generated by Django 4.0.5 on 2022-07-23 22:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source_link', models.TextField(max_length=2000)),
                ('demo_link', models.TextField(max_length=2000)),
            ],
        ),
    ]
