# Generated by Django 4.0.5 on 2022-07-23 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
