# Generated by Django 4.0.5 on 2022-07-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_reviews_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='body',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
