# Generated by Django 4.0.5 on 2022-07-24 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_reviews_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='project.tags'),
        ),
    ]
