# Generated by Django 4.0.5 on 2022-07-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_tags_project_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag',
            new_name='name',
        ),
    ]
