# Generated by Django 4.0.5 on 2022-09-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_location'),
        ('project', '0012_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('project', 'owner')},
        ),
    ]
