# Generated by Django 4.0.5 on 2022-09-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_location'),
        ('project', '0013_reviews_owner_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
