# Generated by Django 4.0.5 on 2022-07-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_skills_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='project',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='skills',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
