# Generated by Django 4.0.5 on 2022-07-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_skills_name_alter_skills_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
