# Generated by Django 4.0.5 on 2022-10-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', 'created']},
        ),
    ]
